### ISSUE TITLE
Read JSON data in `phase-field-hexbin.js` from file rather than cut and paste

### ISSUE THREAD

**Issue by wd15** [tonyfast/chimad-phase-field#7]
See [line 4 in `phase_field_hexbin.js`](https://github.com/wd15/chimad-phase-field/blob/eaf35e63845fae684a10192c46091b5580086823/js/phase_field_hexbin.js#L4) and the JSON is in [`hexbin.json`](https://github.com/wd15/chimad-phase-field/blob/eaf35e63845fae684a10192c46091b5580086823/json/hexbin.json#L1). At the moment it is cut and paste by hand but really should be read by the Javascript file so everything is entirely automated.

**Comment by tonyfast** [comment]
db2a44889d03980296d6f0ca8f6f144f261a7885
